### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by tomoya1600** [tomoya1600/protospace-35717#1]
https://protospace-35717.herokuapp.com/

**Comment by takumi0530** [comment]
@tomoya1600 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラーページに遷移してしまいます。
<img width="630" alt="スクリーンショット 2021-05-27 16 14 29" src="https://user-images.githubusercontent.com/76197191/119782311-0127e480-bf07-11eb-82a7-3a45cf4d07b8.png">


- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページにある投稿者名をクリックすると、別のユーザーの詳細ページに遷移してしまいます。
（画像の場合、青枠の部分をクリックすると「テストユーザー２」のユーザー詳細ページに遷移してしまいます。）
<img width="1100" alt="スクリーンショット 2021-05-27 16 13 44" src="https://user-images.githubusercontent.com/76197191/119782302-fcfbc700-bf06-11eb-97b7-d86e6f6b02eb.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tomoya1600** [comment]
修正いたしました。
再度確認よろしくお願いします

**Comment by takumi0530** [comment]
@tomoya1600 さん、お待たせいたしました！ご提出ありがとうございます‼︎
動作の確認をしたところ、改めて修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページにある投稿者名をクリックすると、トップページに遷移してしまいます。
<img width="270" alt="スクリーンショット 2021-05-28 10 10 15" src="https://user-images.githubusercontent.com/76197191/119915249-13546200-bf9d-11eb-9016-d541978f5964.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tomoya1600** [comment]
user_path修正しました
確認よろしくお願いします。

**Comment by snkw-works** [comment]
@tomoya1600 さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
